### ISSUE TITLE
bug: add new line between agent executions

### ISSUE THREAD

**Issue by maximilien** [i-am-bee/beeai-labs#339]
Currently when running deployed agents, the streaming output mangles the different running agents.
Add a `\n` after agent output.

**Comment by george-lhj** [comment]
should be closed via #339?

**Comment by maximilien** [comment]
@george-lhj I think this is now fixed. Please double check on demo and close.  I cannot replicate anymore.

**Comment by george-lhj** [comment]
The previous PR didn't solve the issue, the new one I opened solves
